# Generated by Django 4.0.2 on 2022-02-02 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('T Shirt', 'T Shirt'), ('Laptop', 'Laptop'), ('Shoe', 'Shoe'), ('Book', 'Book'), ('Bag', 'Bag')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 2, 9, 39, 47, 594094))),
                ('image', models.ImageField(default='img/thumbnail.png', upload_to='')),
            ],
        ),
    ]
